spring:
  main:
    banner-mode: off
  application:
    name: modushop-configuration-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pnd-devops-projects-o7/dsi-webnaire-pn.git
          default-label: main
          search-paths:
            - cloud-services-configurations-files/modushop-hexagonal-archi-micros-app
            - cloud-services-configurations-files/modushop-microservices-base-app
server:
  port: 8888