spring:
  main:
    banner-mode: off
  application:
    name: modushop-configuration-service
  cloud:
    config:
      server:
        git:
          uri: ${CLOUD_CONFIG_GIT_URI}
          default-label: main
          search-paths:
            - cloud-services-configurations-files/modushop-hexagonal-archi-micros-app
            - cloud-services-configurations-files/modushop-microservices-base-app
server:
  port: 8888