spring:
  application:
    name: modu-shop-bs-microservice-order
  datasource:
    url: jdbc:mysql://localhost:3306/orders_db
  
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
server:
  port: 8083