spring:
  application:
    name: modu-shop-gateway-service
  cloud:
    config:
      uri: http://localhost:8888
    gateway:
      server:
        webmvc:
          routes:
            - id: modu-shop-user-microservice
              uri: http://localhost:8081
              predicates:
                - Path=/api/users/**
            - id: modu-shop-product-microservice
              uri: http://localhost:8082
              predicates:
                - Path=/api/products/**
            - id: modu-shop-order-microservice
              uri: http://localhost:8083
              predicates:
                - Path=/api/orders/**
server:
  port: 8080