spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_ROOT_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update # for demo otherwise use flyway
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  cloud:
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://modushop-registration-service:8761/eureka/