spring:
  application:
    name: modushop-hexagonal-archi-bs-ms-product

  datasource:
    url: jdbc:mysql://modushop-db:3306/products_db

  # we tell to microservice there is a idp to validate sent jwt token
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://modushop-keycloak-idp:8079/realms/modushop_app_realm

server:
  port: 8082